version: '2'
services:

  postgres:
    image: postgres
    volumes:
      - ./bancoScripts/TABELAS.sql:/docker-entrypoint-initdb.d/TABELAS.sql
    environment:
      POSTGRES_PASSWORD: "Postgres2024@"
    ports:
      - "5432:5432"
