  spring:

    mvc:
      pathmatch:
        matching-strategy: ant_path_matcher

    datasource:
      url: jdbc:postgresql://localhost:5432/postgres
      username: postgres
      password: Postgres2024@
      driver-class-name: org.postgresql.Driver

  feign:
    client:
      config:
        default:
          connectTimeout: 5000
          readTimeout: 5000

  cpf-api:
    url: localhost:8080